# Generated by Django 3.1.1 on 2020-10-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_link', models.CharField(max_length=2000)),
                ('min_price', models.FloatField()),
                ('Freezed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('our_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
