# Generated by Django 3.1.1 on 2020-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='sku',
            field=models.CharField(default='NFCW13242', max_length=200),
            preserve_default=False,
        ),
    ]
