# Generated by Django 3.1.1 on 2020-10-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addproduct_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=10000)),
                ('web_price', models.CharField(max_length=40)),
                ('offers', models.CharField(max_length=40)),
                ('express', models.CharField(max_length=40)),
                ('sot', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('our_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.addproduct')),
            ],
        ),
    ]
