# Generated by Django 3.1.1 on 2020-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
