# Generated by Django 3.1.1 on 2020-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201006_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
