# Generated by Django 3.1.1 on 2020-10-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='our_price',
            field=models.CharField(max_length=40),
        ),
    ]
